### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MoekaKitamura** [MoekaKitamura/Ontrips#89]
- [ ] ユーザー検索の使用ガイド
- [ ] 中間地点がオカシイとこがある(ゾウのやつとか)
- [ ] blogに写真つけれる
- [ ] それぞれ送られるメール分けれる？？
- [ ] 言語はユーザーによってどんどん増やせる(languageにarrayを許容)
- [ ] acts-as-taggable-on
- [ ] indexでもっと情報を。コメント数とか
- [ ] 目的地検索で、登録が都市の場合、国名では検索できない問題
- [ ] The change you wanted was rejected.のエラー
